name: Dependency Checker & Build CI
on:
    push:
        branches:
            - "**"

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: test
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run Yarn audit
              id: yarn-audit
              run: |
                  yarn audit --json > audit-report.json

            - name: Check for Vulnerabilities
              run: |
                  severityLevel=$(cat audit-report.json | jq '.data.vulnerabilities[].severity | select(. > 7)')
                  if [ -n "$severityLevel" ]; then
                    echo "Vulnerabilities with severity above 7 found. Failing the job."
                    exit 1
                  else
                    echo "No vulnerabilities with severity above 7 found."
                  fi
